### ISSUE TITLE
Doesn't compile (stable-x86_64-pc-windows-msvc, rustc 1.36.0, 2018 ed)

### ISSUE THREAD

**Issue by Hugobros3** [RustAudio/cpal#342]
Straight up refuses to compile when included as a dep ( win10 x64 )

```toml
[dependencies]
hex = "0.3.1"
minifb = "0.13.0"
bitutils = "3.0.0"
spin_sleep = "0.3.7"
cpal = "0.10.0"
```

```
$ cargo build --release
   Compiling proc-macro2 v1.0.5
   Compiling unicode-xid v0.2.0
   Compiling proc-macro2 v0.4.30
   Compiling syn v1.0.5
   Compiling libc v0.2.62
   Compiling cc v1.0.45
   Compiling unicode-xid v0.1.0
   Compiling winapi v0.3.8
   Compiling syn v0.15.44
   Compiling failure_derive v0.1.6
   Compiling autocfg v0.1.6
   Compiling rustc-demangle v0.1.16
   Compiling cfg-if v0.1.10
   Compiling cpal v0.10.0
   Compiling lazy_static v1.4.0
   Compiling cast v0.2.2
   Compiling hex v0.3.2
   Compiling num-traits v0.2.8
   Compiling quote v0.6.13
   Compiling quote v1.0.2
   Compiling backtrace-sys v0.1.31
   Compiling minifb v0.13.0
   Compiling time v0.1.42
   Compiling spin_sleep v0.3.7
   Compiling backtrace v0.3.38
   Compiling bf-impl v1.0.0
   Compiling synstructure v0.12.1
   Compiling bitutils v3.0.0
   Compiling failure v0.1.6
error[E0432]: unresolved import `super::winapi::um::winbase`
  --> C:\Users\Gobrosse\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.10.0\src\host\wasapi\stream.rs:12:5
   |
12 | use super::winapi::um::winbase;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `winbase` in `um`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `cpal`.

To learn more, run the command again with --verbose.
```

Compiles ok when cloning the cpal repo and doing `cargo build --release`

Tried clearing .cargo and "target" in my project dir;

**Comment by est31** [comment]
Thanks for the report! This bug is fixed on master, see #333. The next release will include the fix. In the meantime, you can add a dependency like this to your Cargo.toml:

```toml
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["audiosessiontypes", "audioclient", "coml2api", "combaseapi", "debug", "devpkey", "handleapi", "ksmedia", "mmdeviceapi", "objbase", "std", "synchapi", "winbase", "winuser"] }
```
