### ISSUE TITLE
Version incompatible

### ISSUE THREAD

**Issue by YXL76** [RustAudio/cpal#717]
The latest version on crates.io is `0.14.1`, but the version in `Cargo.toml` is `0.14.0`, which will cause the git patch to not be used.

```toml
[patch.crates-io]
cpal = { git = "https://github.com/RustAudio/cpal", branch = "master" }
```
