### ISSUE TITLE
Release a new version to Crates.io to use cpal with ndk 0.8

### ISSUE THREAD

**Issue by ameknite** [RustAudio/cpal#841]
# Objective:
Use cpal with ndk 0.8

In #820 ndk was updated to 0.8. but a new version to Crates.io has not being released.

alternatives:

```toml
[dependencies]
cpal = { git = "https://github.com/RustAudio/cpal", branch = "master" }
```
